"""
Tools Module
Exports all tools-related models, schemas, and endpoints
"""

from .models import (
    Note,
    Task,
    LogCall,
    Attachment,
    Event,
    CarbonFootprint,
    ChannelConfig,
    Review,
)

from .schemas import (
    NoteBase,
    NoteCreate,
    NoteUpdate,
    NoteResponse,
    TaskBase,
    TaskCreate,
    TaskUpdate,
    TaskResponse,
    LogCallBase,
    LogCallCreate,
    LogCallUpdate,
    LogCallResponse,
    AttachmentBase,
    AttachmentCreate,
    AttachmentUpdate,
    AttachmentResponse,
    EventBase,
    EventCreate,
    EventUpdate,
    EventResponse,
    CarbonFootprintBase,
    CarbonFootprintCreate,
    CarbonFootprintUpdate,
    CarbonFootprintResponse,
    ChannelConfigBase,
    ChannelConfigCreate,
    ChannelConfigUpdate,
    ChannelConfigResponse,
    ReviewBase,
    ReviewCreate,
    ReviewUpdate,
    ReviewResponse,
    NoteFilter,
    TaskFilter,
    LogCallFilter,
    EventFilter,
    BulkTaskUpdate,
    BulkTaskUpdateResult,
    BulkNoteUpdate,
    BulkNoteUpdateResult,
)

from .endpoints import router as tools_router

__all__ = [
    # Models
    "Note",
    "Task",
    "LogCall",
    "Attachment",
    "Event",
    "CarbonFootprint",
    "ChannelConfig",
    "Review",

    # Schemas
    "NoteBase",
    "NoteCreate",
    "NoteUpdate",
    "NoteResponse",
    "TaskBase",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "LogCallBase",
    "LogCallCreate",
    "LogCallUpdate",
    "LogCallResponse",
    "AttachmentBase",
    "AttachmentCreate",
    "AttachmentUpdate",
    "AttachmentResponse",
    "EventBase",
    "EventCreate",
    "EventUpdate",
    "EventResponse",
    "CarbonFootprintBase",
    "CarbonFootprintCreate",
    "CarbonFootprintUpdate",
    "CarbonFootprintResponse",
    "ChannelConfigBase",
    "ChannelConfigCreate",
    "ChannelConfigUpdate",
    "ChannelConfigResponse",
    "ReviewBase",
    "ReviewCreate",
    "ReviewUpdate",
    "ReviewResponse",
    "NoteFilter",
    "TaskFilter",
    "LogCallFilter",
    "EventFilter",
    "BulkTaskUpdate",
    "BulkTaskUpdateResult",
    "BulkNoteUpdate",
    "BulkNoteUpdateResult",

    # Router
    "tools_router",
]
